import ccAiPublicKnowledgeLedger from "./cc-ai-public-knowledge.json";

export const rawSiteContent = {
  sources: [
    {
      id: "approved-main-ui",
      label: "Approved Natural Observatory homepage reference",
      kind: "reference-image",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/design/reference/mainUI-approved.png",
      checkedOn: "2026-07-19",
      notes: "Approved for portfolio composition and design copy; not a standalone stock asset.",
    },
    {
      id: "approved-design-copy",
      label: "V1 content approved for design",
      kind: "document",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/content/v1-design-content.md",
      checkedOn: "2026-07-19",
    },
    {
      id: "foundation-decision",
      label: "Portfolio foundation decision record",
      kind: "document",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/decisions/001-portfolio-foundation.md",
      checkedOn: "2026-07-19",
    },
    {
      id: "approved-public-profile",
      label: "Carlos-approved public profile and biography",
      kind: "user-approval",
      owner: "Carlos Carpio",
      public: true,
      path: "../docs/content/public-profile-approval.md",
      checkedOn: "2026-07-19",
      notes:
        "Approved name, role, privacy-safe location omission, biographies, /contact path, GitHub account, and no additional social links.",
    },
    {
      id: "github-uset82",
      label: "Carlos Carpio public GitHub account",
      kind: "external-page",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82",
      checkedOn: "2026-07-19",
      notes:
        "Carlos approved this as the canonical public GitHub account; volatile repository counts are excluded.",
    },
    {
      id: "public-homepage-observatory",
      label: "Public homepage Observatory frame",
      kind: "external-page",
      owner: "Carlos Carpio",
      public: true,
      url: "https://carloscarpio.dev/",
      checkedOn: "2026-08-28",
      notes:
        "The public homepage includes Enter the Observatory and presents the Observatory as the first-room visual frame, not a separate product.",
    },
    {
      id: "public-strudelai-demo",
      label: "StrudelAI public test build",
      kind: "external-page",
      owner: "Carlos Carpio",
      public: true,
      url: "https://strudelzeroai.app.canner.ca/",
      checkedOn: "2026-08-13",
      notes:
        "Carlos approved this live URL as the public StrudelAI test build. Contributors are welcome via the public GitHub repository.",
    },
    {
      id: "github-kurva",
      label: "Kurva public GitHub repository",
      kind: "repository",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82/blenderSVG",
      checkedOn: "2026-09-25",
      notes:
        "The repository the kurva.agency install instructions clone. Public, and MIT licensed, so the licence label is read from the repository rather than assumed.",
    },
    {
      id: "public-kurva-site",
      label: "Kurva public site",
      kind: "live-demo",
      owner: "Carlos Carpio",
      public: true,
      url: "https://kurva.agency/",
      checkedOn: "2026-09-25",
      notes:
        "Carlos provided this live URL as Kurva's public home and approved publishing it. A live fetch resolved the page and its stated scope. The site says the one-click installer is not published yet, so no installer is claimed here.",
    },
    {
      id: "github-pistola",
      label: "Pistola public GitHub repository",
      kind: "repository",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82/Pistola",
      checkedOn: "2026-09-25",
      notes:
        "Carlos confirmed this uset82 repository as his own project. The repository lists no licence file, so the register reports no licence rather than assuming one.",
    },
    {
      id: "public-pistola-editor",
      label: "Pistola public editor",
      kind: "live-demo",
      owner: "Carlos Carpio",
      public: true,
      url: "https://pistola.canner.app/",
      checkedOn: "2026-09-25",
      notes:
        "Carlos provided the pistolacodex URL and approved publishing the editor. A live fetch resolved the app and its public workspace. The static site describes the intended pipeline; no CAD output, model quality, or AI result is measured or claimed here.",
    },
    {
      id: "github-astraea",
      label: "ASTROEA public GitHub repository",
      kind: "repository",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82/ASTROEA",
      checkedOn: "2026-08-16",
      notes:
        "Carlos directed Cosmos to this public astrology repository. The README describes natal-chart work inspired by astro.com. Educational and personal use; no MIT licence listed.",
    },
    {
      id: "public-astraea-demo",
      label: "ASTROEA public demo",
      kind: "live-demo",
      owner: "Carlos Carpio",
      public: true,
      url: "https://astraia.netlify.app/",
      checkedOn: "2026-08-16",
      notes:
        "Carlos provided this live URL for ASTROEA. A live fetch confirms the astrology app is reachable. Birth details are collected on that origin, not on this portfolio.",
    },
    {
      id: "github-pinaculo",
      label: "Pináculo public GitHub repository",
      kind: "repository",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82/pinaculo",
      checkedOn: "2026-08-16",
      notes:
        "Carlos directed Cosmos to this public numerology repository. Interpretations draw on Carl Jung, per Carlos. No MIT licence listed.",
    },
    {
      id: "public-pinaculo-demo",
      label: "Pináculo public demo",
      kind: "live-demo",
      owner: "Carlos Carpio",
      public: true,
      url: "https://pinaculo.netlify.app/",
      checkedOn: "2026-08-16",
      notes:
        "README and a live fetch confirm the numerology app is reachable. It collects a name and birth date on that origin, not on this portfolio.",
    },
  ],
  metadata: {
    name: "Carlos Alfredo Carpio Meza",
    locale: "en",
    eyebrow: "Engineer · Inventor · Creative Technologist",
    headline: "I turn hidden patterns into working systems.",
    supportingStatement:
      "From artificial intelligence, electronics and future energy to music, astrology and numerology, I transform complex ideas into practical and meaningful experiences.",
    currentFocus:
      "Currently exploring AI agents, resilient energy, creative tools and the patterns connecting technology with human experience.",
    assistantName: "CACM AI",
    /* Direction 1A makes Work the primary action and demotes the Observatory
     * to the discovery route. Both records keep their approved id, label,
     * href, and sources; only which one carries primary emphasis changed. */
    primaryAction: {
      id: "explore-selected-work",
      label: "Explore Selected Work",
      href: "/work",
      kind: "navigation",
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      external: false,
    },
    secondaryAction: {
      id: "enter-observatory",
      label: "Enter the Observatory",
      href: "#selected-systems",
      kind: "navigation",
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      external: false,
    },
    mediaTeaser: {
      eyebrow: "Listen / 02",
      heading: "Music you can hear, and video you can watch.",
      description:
        "Come in whenever you like. The songs live on Suno and the videos on YouTube, and nothing starts until you press play.",
      status: "Listen when you are ready",
      formats: ["Music", "Video"],
      action: {
        id: "visit-sound-foundation",
        label: "Visit Sound",
        href: "/sound",
        kind: "navigation",
        verification: "reference-approved",
        sourceIds: ["approved-main-ui", "foundation-decision"],
        external: false,
      },
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-public-profile", "foundation-decision"],
    },
    personalTeaser: {
      eyebrow: "Astrology + numerology / 03",
      heading: "Come in and try the two apps.",
      description:
        "ASTROEA is astrology inspired by astro.com. Pináculo is numerology with interpretations that draw on Carl Jung. Both are open to try, and both repositories are public on GitHub.",
      status: "Two apps you can try",
      themes: ["ASTROEA", "Pináculo"],
      claimsBoundary:
        "Creative and personal practice—not scientific, medical, or predictive advice.",
      action: {
        id: "enter-cosmos-foundation",
        label: "Enter Cosmos",
        href: "/cosmos",
        kind: "navigation",
        verification: "reference-approved",
        sourceIds: ["approved-design-copy", "foundation-decision"],
        external: false,
      },
      verification: "reference-approved",
      sourceIds: [
        "approved-design-copy",
        "approved-public-profile",
        "foundation-decision",
        "github-astraea",
        "public-astraea-demo",
        "github-pinaculo",
        "public-pinaculo-demo",
      ],
    },
    profileTeaser: {
      eyebrow: "Profile / CV",
      heading: "One practice, many ways of seeing.",
      headingAccent: "many ways",
      role: "Engineer · Inventor · Creative Technologist",
      biography:
        "Carlos works across artificial intelligence, electronics, resilient energy, music, astrology, and numerology. His portfolio connects engineering practice with creative experimentation, presenting verified work separately from prototypes, personal studies, and future concepts.",
      practiceThreads: [
        "AI and electronics",
        "Resilient energy",
        "Chemistry and commercialisation",
        "Music and symbolic systems",
      ],
      primaryAction: {
        id: "explore-profile-cv",
        label: "Explore profile and CV",
        href: "/story",
        kind: "navigation",
        verification: "user-approved",
        sourceIds: ["approved-public-profile", "foundation-decision"],
        external: false,
      },
      secondaryAction: {
        id: "view-github-profile",
        label: "View GitHub",
        href: "https://github.com/uset82",
        kind: "social",
        verification: "verified",
        sourceIds: ["approved-public-profile", "github-uset82"],
        external: true,
      },
      verification: "user-approved",
      sourceIds: ["approved-public-profile", "github-uset82"],
    },
    footer: {
      eyebrow: "Contact / 05",
      /**
       * "See", not "find", and "there", not "exists".
       *
       * Most of what this line points at has no material form: the commercial
       * opportunity inside a thesis does not exist yet, and this footer also
       * closes pages about interpretation and symbol. "Exists" read as a thing
       * on a shelf. The thesis on the contact route turns on seeing rather than
       * finding, and an unseen opportunity is still there.
       */
      heading: "Let’s see what’s already there, and make it work.",
      description:
        "The contact route stays privacy-first: no public email and no form, and an open call in their place.",
      status: "Open call, one public route",
      primaryAction: {
        id: "footer-visit-contact",
        label: "Visit Contact",
        href: "/contact",
        kind: "navigation",
        verification: "user-approved",
        sourceIds: ["approved-public-profile", "foundation-decision"],
        external: false,
      },
      secondaryAction: {
        id: "footer-view-github",
        label: "View GitHub",
        href: "https://github.com/uset82",
        kind: "social",
        verification: "verified",
        sourceIds: ["approved-public-profile", "github-uset82"],
        external: true,
      },
      verification: "reference-approved",
      sourceIds: ["approved-public-profile", "github-uset82", "foundation-decision"],
    },
    verification: "reference-approved",
    sourceIds: ["approved-main-ui", "approved-design-copy", "approved-public-profile"],
  },
  navigation: [
    ["nav-work", "Work", "/work"],
    ["nav-arcade", "Arcade", "/arcade"],
    ["nav-laboratory", "Laboratory", "/laboratory"],
    ["nav-sound", "Sound", "/sound"],
    ["nav-cosmos", "Cosmos", "/cosmos"],
    ["nav-story", "Story", "/story"],
    ["nav-support", "Support", "/support"],
    ["nav-contact", "Contact", "/contact"],
  ].map(([id, label, href]) => ({
    id,
    label,
    href,
    kind: "navigation",
    verification: "reference-approved",
    sourceIds: ["approved-main-ui", "foundation-decision"],
    external: false,
  })),
  projects: [
    {
      id: "project-astraea",
      slug: "astraea",
      title: "ASTROEA",
      tagline: "Natal-chart astrology you can try",
      category: "cosmos",
      status: "prototype",
      featured: true,
      publication: "ready",
      summary:
        "Natal-chart astrology inspired by astro.com, with AI interpretation from the chart data. You can try it on its own site. Creative and personal practice—not scientific, medical, or predictive advice.",
      contribution:
        "Carlos maintains the public ASTROEA repository and provided the live demo URL published on this portfolio.",
      problem:
        "The work explores natal-chart astrology as a creative practice, with interpretation drawn from chart data rather than from this portfolio.",
      constraints: [
        "This portfolio does not host the app, iframe it, or collect names or birth dates.",
        "Birth details are collected only on the app's own origin.",
        "The work is creative and personal practice, not scientific, medical, or predictive advice.",
        "The repository is public to read and is not on this site's MIT contribution list.",
      ],
      approach:
        "The public app generates astrology charts and AI-powered interpretations from details entered on its own site.",
      outcome: "A public GitHub repository and a reachable demo at https://astraia.netlify.app/.",
      owner: "Carlos Carpio",
      verification: "user-approved",
      rights: "pending",
      sourceIds: ["github-astraea", "public-astraea-demo"],
      stack: [],
      links: [
        {
          id: "astraea-demo",
          label: "Try ASTROEA",
          href: "https://astraia.netlify.app/",
          kind: "demo",
          verification: "user-approved",
          sourceIds: ["public-astraea-demo"],
          external: true,
        },
        {
          id: "astraea-repository",
          label: "View ASTROEA",
          href: "https://github.com/uset82/ASTROEA",
          kind: "repository",
          verification: "user-approved",
          sourceIds: ["github-astraea"],
          external: true,
        },
      ],
      media: [],
      presentation: {
        index: "01",
        descriptor: "Natal-chart astrology",
        group: "Cosmos",
      },
    },
    {
      id: "project-pinaculo",
      slug: "pinaculo",
      title: "Pináculo",
      tagline: "Numerology with Jungian interpretations",
      category: "cosmos",
      status: "prototype",
      featured: true,
      publication: "ready",
      summary:
        "A 24-position numerology system. Interpretations draw on Carl Jung. You can try it on its own site. Creative and personal practice—not scientific, medical, or predictive advice.",
      contribution:
        "Carlos maintains the public Pináculo repository and provided the live demo URL published on this portfolio.",
      problem:
        "The work explores a 24-position numerology system as a creative practice, with interpretations that draw on Carl Jung.",
      constraints: [
        "This portfolio does not host the app, iframe it, or collect names or birth dates.",
        "Name and birth date are collected only on the app's own origin.",
        "The work is creative and personal practice, not scientific, medical, or predictive advice.",
        "The repository is public to read and is not on this site's MIT contribution list.",
      ],
      approach:
        "The public app runs the numerology system and its interpretations on its own site, separate from this portfolio.",
      outcome: "A public GitHub repository and a reachable demo at https://pinaculo.netlify.app/.",
      owner: "Carlos Carpio",
      verification: "user-approved",
      rights: "pending",
      sourceIds: ["github-pinaculo", "public-pinaculo-demo"],
      stack: [],
      links: [
        {
          id: "pinaculo-demo",
          label: "Try Pináculo",
          href: "https://pinaculo.netlify.app/",
          kind: "demo",
          verification: "user-approved",
          sourceIds: ["public-pinaculo-demo"],
          external: true,
        },
        {
          id: "pinaculo-repository",
          label: "View Pináculo",
          href: "https://github.com/uset82/pinaculo",
          kind: "repository",
          verification: "user-approved",
          sourceIds: ["github-pinaculo"],
          external: true,
        },
      ],
      media: [],
      presentation: {
        index: "02",
        descriptor: "24-position numerology",
        group: "Cosmos",
      },
    },
    {
      id: "project-future-energy",
      slug: "future-energy",
      title: "Future Energy",
      tagline: "Adaptive flow systems",
      category: "energy",
      status: "concept",
      featured: true,
      publication: "hold",
      summary:
        "A Laboratory thread for resilient energy systems. It is not a shipped product, working device, or live energy service on this site.",
      conceptStatement:
        "Future Energy is a Laboratory thread for resilient energy systems. It is not represented here as a functioning device, live service, or published case study.",
      owner: "Carlos Carpio",
      verification: "reference-approved",
      rights: "pending",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      stack: [],
      links: [],
      media: [],
      presentation: {
        index: "03",
        descriptor: "Adaptive flow systems",
        group: "Laboratory",
      },
    },
    {
      id: "project-kurva",
      slug: "kurva",
      title: "Kurva",
      tagline: "A design canvas for characters, SVG and Blender",
      category: "creative-tools",
      status: "prototype",
      featured: true,
      publication: "ready",
      summary:
        "A local design canvas that carries one character from a picture to clean, layered SVG, with an optional Blender preview and an agent you switch on yourself. Free and open source, and it runs on your machine. The one-click installer is not published yet.",
      contribution:
        "Carlos builds and maintains Kurva, and publishes its repository, plan and site.",
      problem:
        "Turning a drawing or a photo into clean, editable vector art usually means handing the file to a service that keeps it. Kurva is built around the opposite arrangement: the tracing, the SVG and the Blender job stay on the machine that started them.",
      constraints: [
        "The repository publishes a phase checklist; unfinished phases are stated as unfinished rather than implied by the marketing page.",
        "The site says there is no one-click installer yet, so installation runs from source code and no installer is claimed.",
        "Blender is optional and previews work on an explicit copy, not on the original scene.",
        "Remote AI stays off until it is switched on, and the provider key is held by the local host rather than exposed to the browser.",
        "Tracing produces layered vectors, not a rig; rigging and animation are left to the user.",
      ],
      approach:
        "A Studio host runs locally and listens only on loopback behind a token, so pictures, SVG and Blender jobs are processed by default on the same computer that requested them. The canvas edits real pages, layers and paths rather than a picture of paths, and every SVG is sanitized on export with a built-in fallback. When an agent is switched on, the edit is previewed before it is applied or rejected, and coding agents such as Codex, Claude Code and Cursor can connect over MCP.",
      outcome:
        "A public MIT-licensed repository and a live site at https://kurva.agency/ that documents the pipeline, the local-processing boundary and the phase plan.",
      learnings: [
        "A local-first design tool is mostly an evidence problem: every capability it claims has to be checkable in the repository or in the running app.",
        "Keeping the provider key host-side and the host on loopback is what makes optional AI a choice rather than an exposure.",
      ],
      year: 2026,
      owner: "Carlos Carpio",
      verification: "user-approved",
      rights: "owned",
      sourceIds: ["github-kurva", "public-kurva-site"],
      stack: ["TypeScript", "Node.js 22", "SVG", "Blender", "MCP", "OpenRouter"],
      links: [
        {
          id: "kurva-site",
          label: "Open Kurva",
          href: "https://kurva.agency/",
          kind: "demo",
          verification: "user-approved",
          sourceIds: ["public-kurva-site"],
          external: true,
        },
        {
          id: "kurva-repository",
          label: "View Kurva",
          href: "https://github.com/uset82/blenderSVG",
          kind: "repository",
          verification: "user-approved",
          sourceIds: ["github-kurva"],
          external: true,
        },
      ],
      media: [],
      presentation: {
        index: "04",
        descriptor: "Local SVG and Blender canvas",
        group: "Work",
      },
    },
    {
      id: "project-pistola",
      slug: "pistola",
      title: "Pistola",
      tagline: "Say the object, get a model you can edit",
      category: "creative-tools",
      status: "prototype",
      featured: true,
      publication: "ready",
      summary:
        "An AI-native 3D editor: describe an object or drop in a sketch and it becomes an editable scene you refine in place. The editor is open with no account wall. The static site describes the intended pipeline; it does not report a measured CAD result.",
      contribution: "Carlos built Pistola and maintains the public repository and its editor.",
      problem:
        "Most 3D and CAD tooling asks a person to learn a scene graph and a modelling vocabulary before they can make anything. Pistola starts from plain language and keeps the result editable, so the first draft of a shape does not have to be the final model.",
      constraints: [
        "The pipeline is described as a design, not as a benchmark: no generation accuracy, model quality, or timing is measured or claimed here.",
        "The static site is a description of the editor rather than the editor itself; the live workspace is a separate deployment.",
        "FreeCAD is used as an execution engine for sketches, extrudes and fillets, so CAD output depends on that pipeline running.",
        "The repository publishes no licence file, so no licence is claimed.",
        "Planning and generation depend on the model the operator has installed through their own OpenRouter key.",
      ],
      approach:
        "A prompt or sketch is interpreted into a brief covering geometry, materials and constraints, and that brief becomes editor steps: scene nodes, sketches, or a CAD generation job. The steps run in the live editor, where walls, levels, items and CAD bodies share one scene graph that can be selected, undone and revised. FreeCAD handles sketches, extrudes and fillets, and Cursor, VS Code or Codex can drive the same workspace over MCP.",
      outcome:
        "A public repository at github.com/uset82/Pistola and a live editor at https://pistola.canner.app/ with an open public workspace.",
      learnings: [
        "A chat interface only helps a 3D tool when the result stays a real scene graph the user can still select and undo.",
        "Letting existing coding agents drive the same workspace over MCP avoided building a second, weaker control surface.",
      ],
      year: 2026,
      owner: "Carlos Carpio",
      verification: "user-approved",
      rights: "owned",
      sourceIds: ["github-pistola", "public-pistola-editor"],
      stack: ["TypeScript", "Next.js", "Python", "FreeCAD", "MCP", "OpenRouter"],
      links: [
        {
          id: "pistola-editor",
          label: "Open the workspace",
          href: "https://pistola.canner.app/",
          kind: "demo",
          verification: "user-approved",
          sourceIds: ["public-pistola-editor"],
          external: true,
        },
        {
          id: "pistola-repository",
          label: "View Pistola",
          href: "https://github.com/uset82/Pistola",
          kind: "repository",
          verification: "user-approved",
          sourceIds: ["github-pistola"],
          external: true,
        },
      ],
      media: [],
      presentation: {
        index: "05",
        descriptor: "Prompt-driven 3D and CAD editor",
        group: "Work",
      },
    },
  ],
  laboratoryConcepts: [
    {
      id: "laboratory-electronics-ai",
      artifactId: "electronics-ai",
      title: "Electronics / AI",
      descriptor: "Protected modular concept",
      status: "concept",
      statusLabel: "Concept only",
      href: "/laboratory",
      summary:
        "A visual and navigational Laboratory concept for modular electronics and AI work—not a functioning computer, proprietary board, trained model, or live system.",
      boundary:
        "No hardware performance, AI inference, live data, product availability, or ownership of a manufactured device is claimed.",
      verification: "reference-approved",
      rights: "not-applicable",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
    },
    {
      id: "laboratory-aerial-systems",
      artifactId: "drone",
      title: "Aerial systems",
      descriptor: "Guarded camera-drone concept",
      status: "concept",
      statusLabel: "Concept only",
      href: "/laboratory",
      summary:
        "A visual and navigational Laboratory concept for a protected-rotor camera drone with a sparse bounded stabilization cycle—not a functioning aircraft or autonomous system.",
      boundary:
        "No flight performance, autonomous operation, working flight controller, camera capability, production readiness, or ownership of manufactured drone hardware is claimed.",
      verification: "reference-approved",
      rights: "not-applicable",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
    },
  ],
  mediaWorks: [],
  experiences: [],
  education: [],
  trips: [],
  hobbies: [],
  knowledgeRecords: ccAiPublicKnowledgeLedger.records,
};
