import ccAiPublicKnowledgeLedger from "./cc-ai-public-knowledge.json";

export const rawSiteContent = {
  sources: [
    {
      id: "approved-main-ui",
      label: "Approved Natural Observatory homepage reference",
      kind: "reference-image",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/design/reference/mainUI-approved.png",
      checkedOn: "2026-07-19",
      notes: "Approved for portfolio composition and design copy; not a standalone stock asset.",
    },
    {
      id: "approved-design-copy",
      label: "V1 content approved for design",
      kind: "document",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/content/v1-design-content.md",
      checkedOn: "2026-07-19",
    },
    {
      id: "foundation-decision",
      label: "Portfolio foundation decision record",
      kind: "document",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/decisions/001-portfolio-foundation.md",
      checkedOn: "2026-07-19",
    },
    {
      id: "approved-public-profile",
      label: "Carlos-approved public profile and biography",
      kind: "user-approval",
      owner: "Carlos Carpio",
      public: true,
      path: "../docs/content/public-profile-approval.md",
      checkedOn: "2026-07-19",
      notes:
        "Approved name, role, privacy-safe location omission, biographies, /contact path, GitHub account, and no additional social links.",
    },
    {
      id: "github-uset82",
      label: "Carlos Carpio public GitHub account",
      kind: "external-page",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82",
      checkedOn: "2026-07-19",
      notes:
        "Carlos approved this as the canonical public GitHub account; volatile repository counts are excluded.",
    },
    {
      id: "public-homepage-observatory",
      label: "Public homepage Observatory frame",
      kind: "external-page",
      owner: "Carlos Carpio",
      public: true,
      url: "https://carloscarpio.up.railway.app/",
      checkedOn: "2026-08-13",
      notes:
        "The public homepage includes Enter the Observatory and presents the Observatory as the first-room visual frame, not a separate product.",
    },
    {
      id: "public-strudelai-demo",
      label: "StrudelAI public test build",
      kind: "external-page",
      owner: "Carlos Carpio",
      public: true,
      url: "https://strudelzeroai.app.canner.ca/",
      checkedOn: "2026-08-13",
      notes:
        "Carlos approved this live URL as the public StrudelAI test build. Contributors are welcome via the public GitHub repository.",
    },
    {
      id: "github-astraea",
      label: "ASTROEA public GitHub repository",
      kind: "repository",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82/ASTROEA",
      checkedOn: "2026-08-16",
      notes:
        "Carlos directed Cosmos to this public astrology repository. The README describes natal-chart work inspired by astro.com. Educational and personal use; no MIT licence listed.",
    },
    {
      id: "public-astraea-demo",
      label: "ASTROEA public demo",
      kind: "live-demo",
      owner: "Carlos Carpio",
      public: true,
      url: "https://astraia.netlify.app/",
      checkedOn: "2026-08-16",
      notes:
        "Carlos provided this live URL for ASTROEA. A live fetch confirms the astrology app is reachable. Birth details are collected on that origin, not on this portfolio.",
    },
    {
      id: "github-pinaculo",
      label: "Pináculo public GitHub repository",
      kind: "repository",
      owner: "Carlos Carpio",
      public: true,
      url: "https://github.com/uset82/pinaculo",
      checkedOn: "2026-08-16",
      notes:
        "Carlos directed Cosmos to this public numerology repository. Interpretations draw on Carl Jung, per Carlos. No MIT licence listed.",
    },
    {
      id: "public-pinaculo-demo",
      label: "Pináculo public demo",
      kind: "live-demo",
      owner: "Carlos Carpio",
      public: true,
      url: "https://pinaculo.netlify.app/",
      checkedOn: "2026-08-16",
      notes:
        "README and a live fetch confirm the numerology app is reachable. It collects a name and birth date on that origin, not on this portfolio.",
    },
  ],
  metadata: {
    name: "Carlos Alfredo Carpio Meza",
    locale: "en",
    eyebrow: "Engineer · Inventor · Creative Technologist",
    headline: "I turn hidden patterns into working systems.",
    supportingStatement:
      "From artificial intelligence, electronics and future energy to music, astrology and numerology, I transform complex ideas into practical and meaningful experiences.",
    currentFocus:
      "Currently exploring AI agents, resilient energy, creative tools and the patterns connecting technology with human experience.",
    assistantName: "CACM AI",
    /* Direction 1A makes Work the primary action and demotes the Observatory
     * to the discovery route. Both records keep their approved id, label,
     * href, and sources; only which one carries primary emphasis changed. */
    primaryAction: {
      id: "explore-selected-work",
      label: "Explore Selected Work",
      href: "/work",
      kind: "navigation",
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      external: false,
    },
    secondaryAction: {
      id: "enter-observatory",
      label: "Enter the Observatory",
      href: "#selected-systems",
      kind: "navigation",
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      external: false,
    },
    mediaTeaser: {
      eyebrow: "Listen / 02",
      heading: "Music you can hear, and video you can watch.",
      description:
        "Come in whenever you like. The songs live on Suno and the videos on YouTube, and nothing starts until you press play.",
      status: "Listen when you are ready",
      formats: ["Music", "Video"],
      action: {
        id: "visit-sound-foundation",
        label: "Visit Sound",
        href: "/sound",
        kind: "navigation",
        verification: "reference-approved",
        sourceIds: ["approved-main-ui", "foundation-decision"],
        external: false,
      },
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-public-profile", "foundation-decision"],
    },
    personalTeaser: {
      eyebrow: "Astrology + numerology / 03",
      heading: "Come in and try the two apps.",
      description:
        "ASTROEA is astrology inspired by astro.com. Pináculo is numerology with interpretations that draw on Carl Jung. Both are open to try, and both repositories are public on GitHub.",
      status: "Two apps you can try",
      themes: ["ASTROEA", "Pináculo"],
      claimsBoundary:
        "Creative and personal practice—not scientific, medical, or predictive advice.",
      action: {
        id: "enter-cosmos-foundation",
        label: "Enter Cosmos",
        href: "/cosmos",
        kind: "navigation",
        verification: "reference-approved",
        sourceIds: ["approved-design-copy", "foundation-decision"],
        external: false,
      },
      verification: "reference-approved",
      sourceIds: [
        "approved-design-copy",
        "approved-public-profile",
        "foundation-decision",
        "github-astraea",
        "public-astraea-demo",
        "github-pinaculo",
        "public-pinaculo-demo",
      ],
    },
    profileTeaser: {
      eyebrow: "Profile / CV",
      heading: "One practice, many ways of seeing.",
      headingAccent: "many ways",
      role: "Engineer · Inventor · Creative Technologist",
      biography:
        "Carlos works across artificial intelligence, electronics, resilient energy, music, astrology, and numerology. His portfolio connects engineering practice with creative experimentation, presenting verified work separately from prototypes, personal studies, and future concepts.",
      practiceThreads: ["AI and electronics", "Resilient energy", "Music and symbolic systems"],
      primaryAction: {
        id: "explore-profile-cv",
        label: "Explore profile and CV",
        href: "/story",
        kind: "navigation",
        verification: "user-approved",
        sourceIds: ["approved-public-profile", "foundation-decision"],
        external: false,
      },
      secondaryAction: {
        id: "view-github-profile",
        label: "View GitHub",
        href: "https://github.com/uset82",
        kind: "social",
        verification: "verified",
        sourceIds: ["approved-public-profile", "github-uset82"],
        external: true,
      },
      verification: "user-approved",
      sourceIds: ["approved-public-profile", "github-uset82"],
    },
    footer: {
      eyebrow: "Contact / 05",
      heading: "Let’s turn a difficult idea into a working system.",
      description:
        "The contact route remains privacy-first while the final public email or form decision is still open.",
      status: "Public contact method pending",
      primaryAction: {
        id: "footer-visit-contact",
        label: "Visit Contact",
        href: "/contact",
        kind: "navigation",
        verification: "user-approved",
        sourceIds: ["approved-public-profile", "foundation-decision"],
        external: false,
      },
      secondaryAction: {
        id: "footer-view-github",
        label: "View GitHub",
        href: "https://github.com/uset82",
        kind: "social",
        verification: "verified",
        sourceIds: ["approved-public-profile", "github-uset82"],
        external: true,
      },
      verification: "reference-approved",
      sourceIds: ["approved-public-profile", "github-uset82", "foundation-decision"],
    },
    verification: "reference-approved",
    sourceIds: ["approved-main-ui", "approved-design-copy", "approved-public-profile"],
  },
  navigation: [
    ["nav-work", "Work", "/work"],
    ["nav-arcade", "Arcade", "/arcade"],
    ["nav-laboratory", "Laboratory", "/laboratory"],
    ["nav-sound", "Sound", "/sound"],
    ["nav-cosmos", "Cosmos", "/cosmos"],
    ["nav-story", "Story", "/story"],
    ["nav-support", "Support", "/support"],
    ["nav-contact", "Contact", "/contact"],
  ].map(([id, label, href]) => ({
    id,
    label,
    href,
    kind: "navigation",
    verification: "reference-approved",
    sourceIds: ["approved-main-ui", "foundation-decision"],
    external: false,
  })),
  projects: [
    {
      id: "project-astraea",
      slug: "astraea",
      title: "ASTROEA",
      tagline: "Natal-chart astrology you can try",
      category: "cosmos",
      status: "prototype",
      featured: true,
      publication: "ready",
      summary:
        "Natal-chart astrology inspired by astro.com, with AI interpretation from the chart data. You can try it on its own site. Creative and personal practice—not scientific, medical, or predictive advice.",
      contribution:
        "Carlos maintains the public ASTROEA repository and provided the live demo URL published on this portfolio.",
      problem:
        "The work explores natal-chart astrology as a creative practice, with interpretation drawn from chart data rather than from this portfolio.",
      constraints: [
        "This portfolio does not host the app, iframe it, or collect names or birth dates.",
        "Birth details are collected only on the app's own origin.",
        "The work is creative and personal practice, not scientific, medical, or predictive advice.",
        "The repository is public to read and is not on this site's MIT contribution list.",
      ],
      approach:
        "The public app generates astrology charts and AI-powered interpretations from details entered on its own site.",
      outcome: "A public GitHub repository and a reachable demo at https://astraia.netlify.app/.",
      owner: "Carlos Carpio",
      verification: "user-approved",
      rights: "pending",
      sourceIds: ["github-astraea", "public-astraea-demo"],
      stack: [],
      links: [
        {
          id: "astraea-demo",
          label: "Try ASTROEA",
          href: "https://astraia.netlify.app/",
          kind: "demo",
          verification: "user-approved",
          sourceIds: ["public-astraea-demo"],
          external: true,
        },
        {
          id: "astraea-repository",
          label: "View ASTROEA",
          href: "https://github.com/uset82/ASTROEA",
          kind: "repository",
          verification: "user-approved",
          sourceIds: ["github-astraea"],
          external: true,
        },
      ],
      media: [],
      presentation: {
        index: "01",
        descriptor: "Natal-chart astrology",
        group: "Cosmos",
      },
    },
    {
      id: "project-pinaculo",
      slug: "pinaculo",
      title: "Pináculo",
      tagline: "Numerology with Jungian interpretations",
      category: "cosmos",
      status: "prototype",
      featured: true,
      publication: "ready",
      summary:
        "A 24-position numerology system. Interpretations draw on Carl Jung. You can try it on its own site. Creative and personal practice—not scientific, medical, or predictive advice.",
      contribution:
        "Carlos maintains the public Pináculo repository and provided the live demo URL published on this portfolio.",
      problem:
        "The work explores a 24-position numerology system as a creative practice, with interpretations that draw on Carl Jung.",
      constraints: [
        "This portfolio does not host the app, iframe it, or collect names or birth dates.",
        "Name and birth date are collected only on the app's own origin.",
        "The work is creative and personal practice, not scientific, medical, or predictive advice.",
        "The repository is public to read and is not on this site's MIT contribution list.",
      ],
      approach:
        "The public app runs the numerology system and its interpretations on its own site, separate from this portfolio.",
      outcome: "A public GitHub repository and a reachable demo at https://pinaculo.netlify.app/.",
      owner: "Carlos Carpio",
      verification: "user-approved",
      rights: "pending",
      sourceIds: ["github-pinaculo", "public-pinaculo-demo"],
      stack: [],
      links: [
        {
          id: "pinaculo-demo",
          label: "Try Pináculo",
          href: "https://pinaculo.netlify.app/",
          kind: "demo",
          verification: "user-approved",
          sourceIds: ["public-pinaculo-demo"],
          external: true,
        },
        {
          id: "pinaculo-repository",
          label: "View Pináculo",
          href: "https://github.com/uset82/pinaculo",
          kind: "repository",
          verification: "user-approved",
          sourceIds: ["github-pinaculo"],
          external: true,
        },
      ],
      media: [],
      presentation: {
        index: "02",
        descriptor: "24-position numerology",
        group: "Cosmos",
      },
    },
    {
      id: "project-future-energy",
      slug: "future-energy",
      title: "Future Energy",
      tagline: "Adaptive flow systems",
      category: "energy",
      status: "concept",
      featured: true,
      publication: "hold",
      summary:
        "A Laboratory thread for resilient energy systems. It is not a shipped product, working device, or live energy service on this site.",
      conceptStatement:
        "Future Energy is a Laboratory thread for resilient energy systems. It is not represented here as a functioning device, live service, or published case study.",
      owner: "Carlos Carpio",
      verification: "reference-approved",
      rights: "pending",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      stack: [],
      links: [],
      media: [],
      presentation: {
        index: "03",
        descriptor: "Adaptive flow systems",
        group: "Laboratory",
      },
    },
  ],
  laboratoryConcepts: [
    {
      id: "laboratory-electronics-ai",
      artifactId: "electronics-ai",
      title: "Electronics / AI",
      descriptor: "Protected modular concept",
      status: "concept",
      statusLabel: "Concept only",
      href: "/laboratory",
      summary:
        "A visual and navigational Laboratory concept for modular electronics and AI work—not a functioning computer, proprietary board, trained model, or live system.",
      boundary:
        "No hardware performance, AI inference, live data, product availability, or ownership of a manufactured device is claimed.",
      verification: "reference-approved",
      rights: "not-applicable",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
    },
    {
      id: "laboratory-aerial-systems",
      artifactId: "drone",
      title: "Aerial systems",
      descriptor: "Guarded camera-drone concept",
      status: "concept",
      statusLabel: "Concept only",
      href: "/laboratory",
      summary:
        "A visual and navigational Laboratory concept for a protected-rotor camera drone with a sparse bounded stabilization cycle—not a functioning aircraft or autonomous system.",
      boundary:
        "No flight performance, autonomous operation, working flight controller, camera capability, production readiness, or ownership of manufactured drone hardware is claimed.",
      verification: "reference-approved",
      rights: "not-applicable",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
    },
  ],
  mediaWorks: [],
  experiences: [],
  education: [],
  trips: [],
  hobbies: [],
  knowledgeRecords: ccAiPublicKnowledgeLedger.records,
};
