export const rawSiteContent = {
  sources: [
    {
      id: "approved-main-ui",
      label: "Approved Natural Observatory homepage reference",
      kind: "reference-image",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/design/reference/mainUI-approved.png",
      checkedOn: "2026-07-19",
      notes: "Approved for portfolio composition and design copy; not a standalone stock asset.",
    },
    {
      id: "approved-design-copy",
      label: "V1 content approved for design",
      kind: "document",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/content/v1-design-content.md",
      checkedOn: "2026-07-19",
    },
    {
      id: "foundation-decision",
      label: "Portfolio foundation decision record",
      kind: "document",
      owner: "Carlos Carpio",
      public: false,
      path: "../docs/decisions/001-portfolio-foundation.md",
      checkedOn: "2026-07-19",
    },
  ],
  metadata: {
    name: "Carlos Carpio",
    locale: "en",
    eyebrow: "Engineer · Inventor · Creative Technologist",
    headline: "I turn hidden patterns into working systems.",
    supportingStatement:
      "From artificial intelligence, electronics and future energy to music, astrology and numerology, I transform complex ideas into practical and meaningful experiences.",
    currentFocus:
      "Currently exploring AI agents, resilient energy, creative tools and the patterns connecting technology with human experience.",
    assistantName: "CC AI",
    primaryAction: {
      id: "enter-observatory",
      label: "Enter the Observatory",
      href: "#selected-systems",
      kind: "navigation",
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      external: false,
    },
    secondaryAction: {
      id: "explore-selected-work",
      label: "Explore Selected Work",
      href: "/work",
      kind: "navigation",
      verification: "reference-approved",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      external: false,
    },
    verification: "reference-approved",
    sourceIds: ["approved-main-ui", "approved-design-copy"],
  },
  navigation: [
    ["nav-work", "Work", "/work"],
    ["nav-laboratory", "Laboratory", "/laboratory"],
    ["nav-sound", "Sound", "/sound"],
    ["nav-cosmos", "Cosmos", "/cosmos"],
    ["nav-story", "Story", "/story"],
    ["nav-contact", "Contact", "/contact"],
  ].map(([id, label, href]) => ({
    id,
    label,
    href,
    kind: "navigation",
    verification: "reference-approved",
    sourceIds: ["approved-main-ui", "foundation-decision"],
    external: false,
  })),
  projects: [
    {
      id: "project-astraea",
      slug: "astraea",
      title: "ASTRAEA",
      tagline: "Celestial intelligence",
      category: "cosmos",
      status: "concept",
      featured: true,
      publication: "hold",
      summary:
        "A named system in the approved Observatory composition; its case study remains intentionally unpublished while source material is verified.",
      conceptStatement:
        "ASTRAEA represents the celestial-pattern branch of the Observatory and currently functions as an approved visual and navigational concept only.",
      owner: "Carlos Carpio",
      verification: "reference-approved",
      rights: "pending",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      stack: [],
      links: [],
      media: [],
      presentation: {
        index: "01",
        descriptor: "Celestial intelligence",
        group: "Cosmos",
      },
    },
    {
      id: "project-pinaculo",
      slug: "pinaculo",
      title: "PINÁCULO",
      tagline: "Numerological engine",
      category: "cosmos",
      status: "concept",
      featured: true,
      publication: "hold",
      summary:
        "A named system in the approved Observatory composition; its case study remains intentionally unpublished while source material is verified.",
      conceptStatement:
        "PINÁCULO represents the numerological-pattern branch of the Observatory and currently functions as an approved visual and navigational concept only.",
      owner: "Carlos Carpio",
      verification: "reference-approved",
      rights: "pending",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      stack: [],
      links: [],
      media: [],
      presentation: {
        index: "02",
        descriptor: "Numerological engine",
        group: "Cosmos",
      },
    },
    {
      id: "project-future-energy",
      slug: "future-energy",
      title: "Future Energy",
      tagline: "Adaptive flow systems",
      category: "energy",
      status: "concept",
      featured: true,
      publication: "hold",
      summary:
        "A named system in the approved Observatory composition; its case study remains intentionally unpublished while source material is verified.",
      conceptStatement:
        "Future Energy represents the resilient-energy branch of the Observatory and currently functions as an approved visual and navigational concept only.",
      owner: "Carlos Carpio",
      verification: "reference-approved",
      rights: "pending",
      sourceIds: ["approved-main-ui", "approved-design-copy"],
      stack: [],
      links: [],
      media: [],
      presentation: {
        index: "03",
        descriptor: "Adaptive flow systems",
        group: "Laboratory",
      },
    },
  ],
  mediaWorks: [],
  experiences: [],
  education: [],
  trips: [],
  hobbies: [],
};
