/**
 * The complete set of literal colors permitted in application source.
 * CSS semantic tokens and future Three.js materials must resolve to this contract.
 */
export const naturalPalette = {
  taupe: "#a38772",
  stoneSage: "#c1bfb0",
  mutedSage: "#b1b199",
  sand: "#ecdfcf",
  warmIvory: "#fef4ea",
  clay: "#cfa18a",
  paleSage: "#cccab5",
  offWhite: "#e5dfd3",
  darkSage: "#77715b",
  warmTaupe: "#be967d",
  buff: "#dcc1ac",
  dustyPink: "#e8bdb4",
  parchment: "#e8dfd5",
  stone: "#aea090",
  sceneTaupe: "#9d8a73",
  sceneSand: "#c9b49e",
  linen: "#d7c7b5",
  shadowSage: "#6f6655",
  oak: "#8b755d",
  walnut: "#5f4b35",
  espresso: "#2e2417",
  deepWood: "#4b3520",
  moss: "#69705a",
  deepEspresso: "#2a1d16",
  waterSlate: "#5b6965",
  waterLight: "#87918a",
  pewter: "#9b9d96",
  silver: "#c8c7be",
  textSecondary: "#6e5b4d",
  borderSoft: "#cdb69e",
  // Project Orbit is a user-supplied Claude Design handoff. These values are
  // its sampled warm-black/brass material set, kept named so the isolated
  // instrument can stay faithful without leaking arbitrary literals into UI.
  orbitInk: "#0b0907",
  orbitInkRaised: "#15100c",
  orbitInkPanel: "#21170f",
  orbitBrass: "#b8934f",
  orbitBrassDim: "#8a6a3c",
  orbitBronze: "#5d4526",
  orbitGraphite: "#14100c",
  orbitHousing: "#1a1511",
  orbitIvory: "#f4e3c6",
  orbitBrightBrass: "#ffe0ac",
  orbitKeyLight: "#ffd9a3",
  orbitRimLight: "#ffc17a",
  orbitCoreLight: "#ffb972",
  orbitBearing: "#d7ae70",
  orbitHalo: "#e8b06a",
  orbitEnvHighlight: "#6b543c",
  orbitEnvMid: "#2b211a",
  orbitEnvDark: "#120e0a",
  orbitEnvBlack: "#070605",
  orbitAmbient: "#4a3a2a",
} as const;

export const threeMaterialPalette = {
  observatoryArchitecture: naturalPalette.parchment,
  ceramicRobot: naturalPalette.offWhite,
  ceramicRobotShadow: naturalPalette.stone,
  waterBasin: naturalPalette.waterSlate,
  waterHighlight: naturalPalette.waterLight,
  astraea: naturalPalette.pewter,
  pinaculo: naturalPalette.oak,
  soundLab: naturalPalette.walnut,
  futureEnergy: naturalPalette.mutedSage,
  electronics: naturalPalette.deepWood,
  warmIndicator: naturalPalette.clay,
} as const;

export type NaturalPaletteColor = (typeof naturalPalette)[keyof typeof naturalPalette];
