// Single source of truth for the Project Orbit.
// Repo URLs verified against brain/github/inventory.json (owner: uset82).
// Entries with destinationType "internal-route" point at routes that exist in
// the current site (/work, /sound, /cosmos, /laboratory). Where a per-project
// route (/work/<slug>) exists in your router, prefer `slug`.

export const PROJECTS = [
  {
    id: "astraea",
    name: "ASTRAEA",
    slug: "astraea",
    description: "Celestial intelligence — chart reading and cosmic pattern work.",
    icon: "constellation",
    category: "astrology",
    destinationType: "github",
    href: "https://github.com/uset82/ASTROEA",
    githubUrl: "https://github.com/uset82/ASTROEA",
    internalRoute: "/cosmos",
    agentId: "astraea",
    enabled: true,
    featured: true,
  },
  {
    id: "pinaculo",
    name: "PINÁCULO",
    slug: "pinaculo",
    description: "Numerological engine built on the pinnacle method.",
    icon: "pyramid",
    category: "numerology",
    destinationType: "github",
    href: "https://github.com/uset82/pinaculo",
    githubUrl: "https://github.com/uset82/pinaculo",
    internalRoute: "/cosmos",
    agentId: "pinaculo",
    enabled: true,
  },
  {
    id: "future-energy",
    name: "FUTURE ENERGY",
    slug: "future-energy",
    description: "Adaptive flow systems for energy and infrastructure.",
    icon: "bolt",
    category: "energy",
    destinationType: "internal-route",
    href: "/work",
    internalRoute: "/work",
    enabled: true,
  },
  {
    id: "sound-lab",
    name: "SOUND LAB",
    slug: "sound",
    description: "The sound foundation — instruments, sessions and releases.",
    icon: "waveform",
    category: "music",
    destinationType: "internal-route",
    href: "/sound",
    internalRoute: "/sound",
    enabled: true,
  },
  {
    id: "repo2agent",
    name: "Repo2Agent",
    slug: "repo2agent",
    description: "Turns a repository into an agent ANA can reason with.",
    icon: "robot",
    category: "research",
    destinationType: "internal-route",
    href: "/laboratory",
    internalRoute: "/laboratory",
    agentId: "repo2agent",
    enabled: true,
  },
  {
    id: "strudelai",
    name: "StrudelAI",
    slug: "strudelai",
    description: "Generative music patterns written as live code.",
    icon: "code",
    category: "music",
    destinationType: "github",
    href: "https://github.com/uset82/StrudelAI",
    githubUrl: "https://github.com/uset82/StrudelAI",
    enabled: true,
  },
  {
    id: "3doodle",
    name: "3Doodle",
    slug: "3doodle",
    description: "Sketch in three dimensions straight in the browser.",
    icon: "cube",
    category: "creative",
    destinationType: "github",
    href: "https://github.com/uset82/3Doodle",
    githubUrl: "https://github.com/uset82/3Doodle",
    enabled: true,
  },
  {
    id: "ifoundyou",
    name: "iFoundYou",
    slug: "ifoundyou",
    description: "Finding people and things through shared signals.",
    icon: "pin",
    category: "tool",
    destinationType: "github",
    href: "https://github.com/uset82/iFoundYou",
    githubUrl: "https://github.com/uset82/iFoundYou",
    enabled: true,
  },
  {
    id: "avatar-studio",
    name: "Avatar Studio",
    slug: "avatar-studio",
    description: "Voice and likeness studio for synthetic presenters.",
    icon: "mic",
    category: "ai",
    destinationType: "github",
    href: "https://github.com/uset82/avatar-studio",
    githubUrl: "https://github.com/uset82/avatar-studio",
    enabled: true,
  },
  {
    id: "smartchatbot",
    name: "SmartChatbot",
    slug: "smartchatbot",
    description: "ANA's conversational layer over the whole portfolio.",
    icon: "chat",
    category: "ai",
    destinationType: "agent",
    href: "#ana=ana",
    agentId: "ana",
    enabled: true,
  },
];

export const ORBIT_CONFIG = {
  radiusX: 7.5,
  radiusZ: 2.95,
  revolutionSeconds: 60, // tune 45–90
  focusAngle: Math.PI / 2, // front-centre of the ellipse
  focusDurationMs: 820,
  bearingBalls: 22,
  hoverSlowFactor: 0.25,
  dragThresholdPx: 5,
  openOnFirstClick: false,
};
